In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_movie=pd.read_csv('tmdb_5000_movies.csv')
data_credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
data_movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
data_credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
data_movie.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [6]:
data_credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [7]:
data_movie.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [8]:
data_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [9]:
data=data_movie.merge(data_credits,on='title')

In [10]:
data.shape

(4809, 23)

In [11]:
 data=data[['id','title','overview','genres','keywords','cast','crew']]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [13]:
data.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
data.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
data.dropna(inplace=True)

In [16]:
data.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [18]:
import ast
ast.literal_eval

In [19]:
data['genres'] = data['genres'].apply(convert)

In [20]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
data['keywords']=data['keywords'].apply(convert)

In [22]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def convert3(obj):
    L=[]
    count=0
    for i in ast.literal_eval(obj):
        if count != 3:
            L.append(i['name'])
            count+=1
        else:
            break
        
    return L

In [24]:
data['cast'] = data['cast'].apply(convert3)

In [25]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def fetch(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [27]:
data['crew'] = data['crew'].apply(fetch)

In [28]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
data['overview'] = data['overview'].apply(lambda x:x.split())

In [30]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
data['genres']=data['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
data['keywords']=data['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [33]:
data['cast'] =data['cast'].apply(lambda x:[i.replace(" ","") for i in x])
data['crew']=data['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [34]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [35]:
data['tags']=data['overview'] + data['genres'] + data['keywords'] + data['cast']  + data['crew']

In [36]:
data.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
df=data[['id','title','tags']]

In [38]:
df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [39]:
df['tags']=df['tags'].apply(lambda x:" ".join(x))

C:\Users\cc\AppData\Local\Temp\ipykernel_13804\2493417758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:" ".join(x))

In [40]:
# df['tags'].apply(lambda x:"".join(x))

In [41]:
df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [42]:
df['tags']=df['tags'].apply(lambda x:x.lower())

C:\Users\cc\AppData\Local\Temp\ipykernel_13804\2034404066.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:x.lower())

In [43]:
df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [46]:
def stem (text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [47]:
df['tags'] = df['tags'].apply(stem)

C:\Users\cc\AppData\Local\Temp\ipykernel_13804\866399325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(stem)

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [49]:
vectors = cv.fit_transform(df['tags']).toarray()

In [50]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
similarity = cosine_similarity(vectors)

In [53]:
similarity.shape

(4806, 4806)

In [54]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        # print(i[0])
        print(df.iloc[i[0]].title)

In [63]:
recommend('Spider-Man 3')

Spider-Man 2
Spider-Man
The Amazing Spider-Man 2
The Amazing Spider-Man
Arachnophobia

In [56]:
## abhi bacha hai deploy karna , website bana na , yt ya hai  https://www.youtube.com/watch?v=1xtrIEwY_zY&t=4052s

In [61]:
data.head(50)

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
5,559,Spider-Man 3,"[The, seemingly, invincible, Spider-Man, goes,...","[Fantasy, Action, Adventure]","[dualidentity, amnesia, sandstorm, loveofone's...","[TobeyMaguire, KirstenDunst, JamesFranco]",[SamRaimi],"[The, seemingly, invincible, Spider-Man, goes,..."
6,38757,Tangled,"[When, the, kingdom's, most, wanted-and, most,...","[Animation, Family]","[hostage, magic, horse, fairytale, musical, pr...","[ZacharyLevi, MandyMoore, DonnaMurphy]",[ByronHoward],"[When, the, kingdom's, most, wanted-and, most,..."
7,99861,Avengers: Age of Ultron,"[When, Tony, Stark, tries, to, jumpstart, a, d...","[Action, Adventure, ScienceFiction]","[marvelcomic, sequel, superhero, basedoncomicb...","[RobertDowneyJr., ChrisHemsworth, MarkRuffalo]",[JossWhedon],"[When, Tony, Stark, tries, to, jumpstart, a, d..."
8,767,Harry Potter and the Half-Blood Prince,"[As, Harry, begins, his, sixth, year, at, Hogw...","[Adventure, Fantasy, Family]","[witch, magic, broom, schoolofwitchcraft, wiza...","[DanielRadcliffe, RupertGrint, EmmaWatson]",[DavidYates],"[As, Harry, begins, his, sixth, year, at, Hogw..."
9,209112,Batman v Superman: Dawn of Justice,"[Fearing, the, actions, of, a, god-like, Super...","[Action, Adventure, Fantasy]","[dccomics, vigilante, superhero, basedoncomicb...","[BenAffleck, HenryCavill, GalGadot]",[ZackSnyder],"[Fearing, the, actions, of, a, god-like, Super..."
10,1452,Superman Returns,"[Superman, returns, to, discover, his, 5-year,...","[Adventure, Fantasy, Action, ScienceFiction]","[savingtheworld, dccomics, invulnerability, se...","[BrandonRouth, KevinSpacey, KateBosworth]",[BryanSinger],"[Superman, returns, to, discover, his, 5-year,..."
11,10764,Quantum of Solace,"[Quantum, of, Solace, continues, the, adventur...","[Adventure, Action, Thriller, Crime]","[killing, undercover, secretagent, britishsecr...","[DanielCraig, OlgaKurylenko, MathieuAmalric]",[MarcForster],"[Quantum, of, Solace, continues, the, adventur..."
12,58,Pirates of the Caribbean: Dead Man's Chest,"[Captain, Jack, Sparrow, works, his, way, out,...","[Adventure, Fantasy, Action]","[witch, fortuneteller, bondage, exoticisland, ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Jack, Sparrow, works, his, way, out,..."
13,57201,The Lone Ranger,"[The, Texas, Rangers, chase, down, a, gang, of...","[Action, Adventure, Western]","[texas, horse, survivor, texasranger, partner,...","[JohnnyDepp, ArmieHammer, WilliamFichtner]",[GoreVerbinski],"[The, Texas, Rangers, chase, down, a, gang, of..."
14,49521,Man of Steel,"[A, young, boy, learns, that, he, has, extraor...","[Action, Adventure, Fantasy, ScienceFiction]","[savingtheworld, dccomics, superhero, basedonc...","[HenryCavill, AmyAdams, MichaelShannon]",[ZackSnyder],"[A, young, boy, learns, that, he, has, extraor..."
15,2454,The Chronicles of Narnia: Prince Caspian,"[One, year, after, their, incredible, adventur...","[Adventure, Family, Fantasy]","[basedonnovel, fictionalplace, brothersisterre...","[BenBarnes, WilliamMoseley, AnnaPopplewell]",[AndrewAdamson],"[One, year, after, their, incredible, adventur..."
16,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th...","[ScienceFiction, Action, Adventure]","[newyork, shield, marvelcomic, superhero, base...","[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon],"[When, an, unexpected, enemy, emerges, and, th..."
17,1865,Pirates of the Caribbean: On Stranger Tides,"[Captain, Jack, Sparrow, crosses, paths, with,...","[Adventure, Action, Fantasy]","[sea, captain, mutiny, sword, primeminister, s...","[JohnnyDepp, PenélopeCruz, IanMcShane]",[RobMarshall],"[Captain, Jack, Sparrow, crosses, paths, with,..."
18,41154,Men in Black 3,"[Agents, J, (Will, Smith), and, K, (Tommy, Lee...","[Action, Comedy, ScienceFiction]","[timetravel, timemachine, alien, fictionalgove...","[WillSmith, TommyLeeJones, JoshBrolin]",[BarrySonnenfeld],"[Agents, J, (Will, Smith), and, K, (Tommy, Lee..."
19,122917,The Hobbit: The Battle of the Five Armies,"[Immediately, after, the, events, of, The, Des...","[Action, Adventure, Fantasy]","[corruption, elves, dwarves, orcs, middle-eart...","[MartinFreeman, IanMcKellen, RichardArmitage]",[PeterJackson],"[Immediately, after, the, events, of, The, Des..."
20,1930,The Amazing Spider-Man,"[Peter, Parker, is, an, outcast, high, schoole...","[Action, Adventure, Fantasy]","[lossoffather, vigilante, serum, marvelcomic, ...","[AndrewGarfield, EmmaStone, RhysIfans]",[MarcWebb],"[Peter, Parker, is, an, outcast, high, schoole..."
21,20662,Robin Hood,"[When, soldier, Robin, happens, upon, the, dyi...","[Action, Adventure]","[robinhood, archer, knight, sherwoodforest, bo...","[RussellCrowe, CateBlanchett, MaxvonSydow]",[RidleyScott],"[When, soldier, Robin, happens, upon, the, dyi..."
22,57158,The Hobbit: The Desolation of Smaug,"[The, Dwarves,, Bilbo, and, Gandalf, have, suc...","[Adventure, Fantasy]","[elves, dwarves, orcs, hobbit, dragon, wizard,...","[MartinFreeman, IanMcKellen, RichardArmitage]",[PeterJackson],"[The, Dwarves,, Bilbo, and, Gandalf, have, suc..."
23,2268,The Golden Compass,"[After, overhearing, a, shocking, secret,, pre...","[Adventure, Fantasy]","[england, compass, experiment, lordship, uncle...","[DakotaBlueRichards, NicoleKidman, DanielCraig]",[ChrisWeitz],"[After, overhearing, a, shocking, secret,, pre..."
24,254,King Kong,"[In, 1933, New, York,, an, overly, ambitious, ...","[Adventure, Drama, Action]","[filmbusiness, screenplay, showbusiness, filmm...","[NaomiWatts, JackBlack, AdrienBrody]",[PeterJackson],"[In, 1933, New, York,, an, overly, ambitious, ..."
25,597,Titanic,"[84, years, later,, a, 101-year-old, woman, na...","[Drama, Romance, Thriller]","[shipwreck, iceberg, ship, panic, titanic, oce...","[KateWinslet, LeonardoDiCaprio, FrancesFisher]",[JamesCameron],"[84, years, later,, a, 101-year-old, woman, na..."
26,271110,Captain America: Civil War,"[Following, the, events, of, Age, of, Ultron,,...","[Adventure, Action, ScienceFiction]","[civilwar, war, marvelcomic, sequel, superhero...","[ChrisEvans, RobertDowneyJr., ScarlettJohansson]",[AnthonyRusso],"[Following, the, events, of, Age, of, Ultron,,..."
27,44833,Battleship,"[When, mankind, beams, a, radio, signal, into,...","[Thriller, Action, Adventure, ScienceFiction]","[fight, u.s.navy, mindreading, hongkong, socce...","[TaylorKitsch, AlexanderSkarsgård, Rihanna]",[PeterBerg],"[When, mankind, beams, a, radio, signal, into,..."
28,135397,Jurassic World,"[Twenty-two, years, after, the, events, of, Ju...","[Action, Adventure, ScienceFiction, Thriller]","[monster, dna, tyrannosaurusrex, velociraptor,...","[ChrisPratt, BryceDallasHoward, IrrfanKhan]",[ColinTrevorrow],"[Twenty-two, years, after, the, events, of, Ju..."
29,37724,Skyfall,"[When, Bond's, latest, assignment, goes, grave...","[Action, Adventure, Thriller]","[spy, secretagent, sociopath, killer, artgalle...","[DanielCraig, JudiDench, JavierBardem]",[SamMendes],"[When, Bond's, latest, assignment, goes, grave..."
30,558,Spider-Man 2,"[Peter, Parker, is, going, through, a, major, ...","[Action, Adventure, Fantasy]","[dualidentity, loveofone'slife, pizzaboy, marv...","[TobeyMaguire, KirstenDunst, JamesFranco]",[SamRaimi],"[Peter, Parker, is, going, through, a, major, ..."
31,68721,Iron Man 3,"[When, Tony, Stark's, world, is, torn, apart, ...","[Action, Adventure, ScienceFiction]","[terrorist, waronterror, tennessee, malibu, ma...","[RobertDowneyJr., GwynethPaltrow, DonCheadle]",[ShaneBlack],"[When, Tony, Stark's, world, is, torn, apart, ..."
32,12155,Alice in Wonderland,"[Alice,, an, unpretentious, and, individual, 1...","[Family, Fantasy, Adventure]","[basedonnovel, fictionalplace, queen, fantasy,...","[MiaWasikowska, JohnnyDepp, AnneHathaway]",[TimBurton],"[Alice,, an, unpretentious, and, individual, 1..."
33,36668,X-Men: The Last Stand,"[When, a, cure, is, found, to, treat, mutation...","[Adventure, Action, ScienceFiction, Thriller]","[mutant, marvelcomic, basedoncomicbook, superh...","[HughJackman, HalleBerry, IanMcKellen]",[BrettRatner],"[When, a, cure, is, found, to, treat, mutation..."
34,62211,Monsters University,"[A, look, at, the, relationship, between, Mike...","[Animation, Family]","[monster, dormitory, games, animation, bestfri...","[BillyCrystal, JohnGoodman, SteveBuscemi]",[DanScanlon],"[A, look, at, the, relationship, between, Mike..."
35,8373,Transformers: Revenge of the Fallen,"[Sam, Witwicky, leaves, the, Autobots, behind,...","[ScienceFiction, Action, Adventure]","[egypt, sun, chaos, symbol, artifact, transfor...","[ShiaLaBeouf, MeganFox, JoshDuhamel]",[MichaelBay],"[Sam, Witwicky, leaves, the, Autobots, behind,..."
36,91314,Transformers: Age of Extinction,"[As, humanity, picks, up, the, pieces,, follow...","[ScienceFiction, Action, Adventure]","[sequel, alien, transformers, giantrobot, robo...","[MarkWahlberg, StanleyTucci, KelseyGrammer]",[MichaelBay],"[As, humanity, picks, up, the, pieces,, follow..."
37,68728,Oz: The Great and Powerful,"[Oscar, Diggs,, a, small-time, circus, illusio...","[Fantasy, Adventure, Family]","[circus, witch, magic, hope, illusion, lost, m...","[JamesFranco, MilaKunis, RachelWeisz]",[SamRaimi],"[Oscar, Diggs,, a, small-time, circus, illusio..."
38,102382,The Amazing Spider-Man 2,"[For, Peter, Parker,, life, is, busy., Between...","[Action, Adventure, Fantasy]","[obsession, marvelcomic, sequel, basedoncomicb...","[AndrewGarfield, EmmaStone, JamieFoxx]",[MarcWebb],"[For, Peter, Parker,, life, is, busy., Between..."
39,20526,TRON: Legacy,"[Sam, Flynn,, the, tech-savvy, and, daring, so...","[Adventure, Action, ScienceFiction]","[artificialintelligence, secretidentity, compu...","[GarrettHedlund, JeffBridges, OliviaWilde]",[JosephKosinski],"[Sam, Flynn,, the, tech-savvy, and, daring, so..."
40,49013,Cars 2,"[Star, race, car, Lightning, McQueen, and, his...","[Animation, Family, Adventure, Comedy]","[carrace, sequel, comedy, anthropomorphism, be...","[OwenWilson, LarrytheCableGuy, MichaelCaine]",[JohnLasseter],"[Star, race, car, Lightning, McQueen, and, his..."
41,44912,Green Lantern,"[For, centuries,, a, small, but, powerful, for...","[Adventure, Action, Thriller, ScienceFiction]","[dccomics, transformation, superhero, alien, a...","[RyanReynolds, BlakeLively, PeterSarsgaard]",[MartinCampbell],"[For, centuries,, a, small, but, powerful, for..."
42,10193,Toy Story 3,"[Woody,, Buzz,, and, the, rest, of, Andy's, to...","[Animation, Family, Comedy]","[hostage, college, toy, barbie, animation, esc...","[TomHanks, TimAllen, NedBeatty]",[LeeUnkrich],"[Woody,, Buzz,, and, the, rest, of, Andy's, to..."
43,534,Terminator Salvation,"[All, grown, up, in, post-apocalyptic, 2018,, ...","[Action, ScienceFiction, Thriller]","[savingtheworld, artificialintelligence, proph...","[ChristianBale, SamWorthington, AntonYelchin]",[McG],"[All, grown, up, in, post-apocalyptic, 2018,, ..."
44,168259,Furious 7,"[Deckard, Shaw, seeks, revenge, against, Domin...",[Action],"[carrace, speed, revenge, suspense, car, race,...","[VinDiesel, PaulWalker, DwayneJohnson]",[JamesWan],"[Deckard, Shaw, seeks, revenge, against, Domin..."
45,72190,World War Z,"[Life, for, former, United, Nations, investiga...","[Action, Drama, Horror, ScienceFiction, Thriller]","[dystopia, apocalypse, zombie, nuclearweapons,...","[BradPitt, MireilleEnos, AbigailHargrove]",[MarcForster],"[Life, for, former, United, Nations, investiga..."
46,127585,X-Men: Days of Future Past,"[The, ultimate, X-Men, ensemble, fights, a, wa...","[Action, Adventure, Fantasy, ScienceFiction]","[1970s, mutant, timetravel, marvelcomic, based...","[HughJackman, JamesMcAvoy, MichaelFassbender]",[BryanSinger],"[The, ultimate, X-Men, ensemble, fights, a, wa..."
47,54138,Star Trek Into Darkness,"[When, the, crew, of, the, Enterprise, is, cal...","[Action, Adventure, ScienceFiction]","[spacecraft, friendship, sequel, futuristic, s...","[ChrisPine, ZacharyQuinto, ZoeSaldana]",[J.J.Abrams],"[When, the, crew, of, the, Enterprise, is, cal..."
48,81005,Jack the Giant Slayer,"[The, story, of, an, ancient, war, that, is, r...","[Action, Family, Fantasy]","[basedonfairytale, giant]","[NicholasHoult, EleanorTomlinson, EwanMcGregor]",[BryanSinger],"[The, story, of, an, ancient, war, that, is, r..."
49,64682,The Great Gatsby,"[An, adaptation, of, F., Scott, Fitzgerald's, ...","[Drama, Romance]","[basedonnovel, infidelity, obsession, hope, 3d]","[LeonardoDiCaprio, TobeyMaguire, CareyMulligan]",[BazLuhrmann],"[An, adaptation, of, F., Scott, Fitzgerald's, ..."